apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
  labels:
    app: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - name: welcome-app
          image: ghcr.io/moronmon/sltr-test-welcomeapp/moronmon/testing/welcome:latest
          ports:
            - containerPort: 5000
