name: DockerBuild_Image

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -f 2.Container-Docker/Dockerfile -t ttl.sh/morownmon_phyton:10m
