name: DockerBuild_Image

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Versioning the Docker Image'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Registry
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.SECRET_PASS }}
    - name: Build the Image
      run: docker build -t ghcr.io/${{ github.repository }}/moronmon/testing/welcome:latest -t ghcr.io/${{ github.repository }}/moronmon/testing/welcome:${{ github.event.inputs.release_tag }} -f 2.Container-Docker/Dockerfile .
    - name: Push to Registry
      run: |
          docker push ghcr.io/${{ github.repository }}/moronmon/testing/welcome:latest
          docker push ghcr.io/${{ github.repository }}/moronmon/testing/welcome:${{ github.event.inputs.release_tag }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to VM
      run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} -p ${{ secrets.VM_PORT  }} 'bash -s' < 3.CICD_GitHubActions/script-deploy.sh
