name: DockerBuild_Image

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Versioning the Docker Image'
        required: true
        # default: 'latest'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Registry
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Image
      run: docker build -t ghcr.io/${{ github.repository }}/moronmon/testing/welcome:latest -t ghcr.io/${{ github.repository }}/moronmon/testing/welcome:${{ github.event.inputs.release_tag }} -f 2.Container-Docker/Dockerfile .
    - name: Push to Registry
      run: |
          docker push ghcr.io/${{ github.repository }}/moronmon/testing/welcome:latest
          docker push ghcr.io/${{ github.repository }}/moronmon/testing/welcome:${{ github.event.inputs.release_tag }}
